Часть: 6 Интеграционное (acceptance) тестирование
Alex-Govorov/qna pull request #3
Opened 2021-03-23 23:38 UTC by Alex-Govorov

2021-03-24 07:17 UTC, vkurennov requested changes

2021-03-24 07:17 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if @answer.user == current_user
1. лучше сравнивать по user_id, чтобы не делать лишний запрос
2. такая проверка понадобится много где, стоит вынести ее в метод `User#author_of?` (и не забудь тесты написать на метод)

2021-03-24 07:17 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if @question.user == current_user
замени на вызов метод `User#author_of?`

2021-03-24 07:17 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:title, :body, :user_id)
user_id в параметрах не передается, мы его через current_user получаем в контроллере

2021-03-24 07:17 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +  - if answer.id
1. лучше использовать метод `persisted?`
2. стоит эту проверку вообще вначале паршала сделать, потому что нет смысла выводить несохраненный ответ

2021-03-24 07:17 UTC, vkurennov commented on config/routes.rb
> +    resources :answers, only: %i[new create destroy]
1. стоит объявить ресурс как shallow, чтобы не передавать вопрос там, где он не нужен (в destroy, например)
2. new не нужен, т.к. форма ответа должна быть на странице questions/show

2021-03-24 07:17 UTC, vkurennov commented on app/controllers/answers_controller.rb
>    def new
new не нужен, т.к. форма ответа должна быть на странице questions/show

2021-03-24 07:17 UTC, vkurennov commented on app/controllers/answers_controller.rb
>        render :new
раз форма ответа должна быть на странице вопроса, то ее (страницу вопроса) и надо здесь рендерить

2021-03-24 07:17 UTC, vkurennov commented on app/views/answers/new.html.slim
> += render template: 'questions/show'
это как раз и означает, что вид не нужен, можно обойтись видом questions/show

2021-03-24 07:17 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>  RSpec.describe AnswersController, type: :controller do
где тесты на destroy? если ты пишешь код в контроллере или модели, его надо покрывать юнит-тестами

2021-03-24 07:17 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +  describe 'DELETE #destroy' do
у тебя условие в контрорллере, значит, надо все варианты проверять, поэтому тут должно быть 2 контекста: для автора и для не-автора

2021-03-24 07:17 UTC, vkurennov commented on spec/feature/answers/destroy_spec.rb
> +    expect(page).to have_content 'Answer successfully deleted.'
этого недостаточно, перед удалением надо убедиться, что текст ответа есть на странице, а после удаления, что его нет

2021-03-24 07:17 UTC, vkurennov commented on spec/feature/answers/destroy_spec.rb
> +    click_on 'Delete'
лучше вообще не показывать ссылку не-автору

2021-03-24 07:17 UTC, vkurennov commented on spec/feature/answers/destroy_spec.rb
> +  scenario "Authenticated user tried deletes someone else's answer" do
нужен похожий сценарий для незалогиненного юзера

2021-03-24 07:17 UTC, vkurennov commented on spec/feature/questions/destroy_spec.rb
> +feature "The author can delete his own question, but cannot delete someone else's question", "
см замчания к аналогичной фиче для ответов

2021-03-24 07:17 UTC, vkurennov commented on spec/feature/questions/show_spec.rb
> +  scenario 'User view question and answers to it' do
тут надо проверить список ответов

2021-03-25 08:05 UTC, vkurennov approved these changes

2021-03-25 08:05 UTC, vkurennov commented on app/models/user.rb
> +    resource.user == self
я же писал: сравнивать нужно по id, чтобы не было лишнего запроса к базе на загрузку ассоциации (проблема n+1 запроса).  а вот **присваивать** лучше по объектам

2021-03-25 08:05 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, params: { id: answer } }.to change(Answer, :count).by(0)
лучше `to_not change(...)`

2021-03-25 08:05 UTC, vkurennov commented on spec/models/user_spec.rb
> +      expect(user.author_of?(question)).to eq true
лучше так: `expect(user).to be_author_of(question)`

работает для любых методов-предикатов (со знаком вопроса), достаточно перенести вызов метода после to/to_not, добавить be_ перед именем метода и убрать знак вопроса

2021-03-25 15:46 UTC, Alex-Govorov commented on app/models/user.rb
> +    resource.user == self
Поменял. Но я не могу понять, как воспроизвести проблему n+1

При сравнениии по id
`resource.user_id == id`
выполняю GET /questions, получаю страницу с 3мя вопросами(2а созданы одним пользователем, 3ий другим). Выполняется 5ть запросов

Started GET "/questions" for 127.0.0.1 at 2021-03-25 18:26:36 +0300
Processing by QuestionsController#index as HTML
  Rendering layout layouts/application.html.slim
  Rendering questions/index.html.slim within layouts/application
  Question Load (3.2ms)  SELECT "questions".* FROM "questions"
  ↳ app/views/questions/index.html.slim:6
  User Load (4.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
  ↳ app/views/questions/_question.html.slim:3
  User Load (3.6ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/views/questions/_question.html.slim:5
  CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
  ↳ app/views/questions/_question.html.slim:3
  User Load (3.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/views/questions/_question.html.slim:3
  Rendered collection of questions/_question.html.slim [3 times] (Duration: 28.4ms | Allocations: 3479)
  Rendered questions/index.html.slim within layouts/application (Duration: 38.2ms | Allocations: 4611)
[Webpacker] Everything's up-to-date. Nothing to do
  Rendered shared/_flash.html.slim (Duration: 0.3ms | Allocations: 51)
  Rendered shared/_nav.html.slim (Duration: 1.0ms | Allocations: 112)
  Rendered layout layouts/application.html.slim (Duration: 55.7ms | Allocations: 7785)
Completed 200 OK in 58ms (Views: 42.6ms | ActiveRecord: 14.3ms | Allocations: 8265)

При сравнениии по объекту получаю абсолютно идентичный результат
`resource.user == self`

Started GET "/questions" for 127.0.0.1 at 2021-03-25 18:40:27 +0300
Processing by QuestionsController#index as HTML
  Rendering layout layouts/application.html.slim
  Rendering questions/index.html.slim within layouts/application
  Question Load (2.7ms)  SELECT "questions".* FROM "questions"
  ↳ app/views/questions/index.html.slim:6
  User Load (3.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
  ↳ app/views/questions/_question.html.slim:3
  User Load (3.5ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/views/questions/_question.html.slim:5
  CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
  ↳ app/views/questions/_question.html.slim:3
  User Load (3.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/views/questions/_question.html.slim:3
  Rendered collection of questions/_question.html.slim [3 times] (Duration: 24.3ms | Allocations: 3482)
  Rendered questions/index.html.slim within layouts/application (Duration: 32.9ms | Allocations: 4614)
[Webpacker] Everything's up-to-date. Nothing to do
  Rendered shared/_flash.html.slim (Duration: 0.2ms | Allocations: 51)
  Rendered shared/_nav.html.slim (Duration: 0.3ms | Allocations: 112)
  Rendered layout layouts/application.html.slim (Duration: 42.3ms | Allocations: 7789)
Completed 200 OK in 44ms (Views: 30.9ms | ActiveRecord: 12.6ms | Allocations: 8271)

2021-03-25 16:10 UTC, merged