Future: Authenticated user can vote question/answer he likes
Alex-Govorov/qna pull request #7
Opened 2021-06-11 04:58 UTC by Alex-Govorov

2021-06-11 10:02 UTC, vkurennov requested changes

2021-06-11 10:02 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +    @params[:can_vote] = vote.valid?
использовать парамсы для ответа, как-то не очнеь выгладит, хотя почему ты так сделал - понимаю. в целом ок, пусть остается, но я бы подумал над другим решением здесь

2021-06-11 10:02 UTC, vkurennov commented on config/routes.rb
> +  post 'vote_up/:resource_type/:resource_id', to: 'votes#vote_up', as: :vote_up
сделай нормальный ресурсный роутинг. тут как раз консерн роутов может пригодиться. по сути, тебе надо объявить ресурс votes с кастомными экшенами (кстати, лучше на стандартных сделать) и вложить его в вопрос и ответ

2021-07-07 08:33 UTC, vkurennov approved these changes

2021-07-07 08:33 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +    vote_response = {}
а зачем по-абрибутам отдельно собирать хеш? принято сразу во время объявления задавать все атрибуты

2021-07-07 08:33 UTC, vkurennov commented on config/routes.rb
> +      post :create, path: ':value', on: :member, as: :new
а зачем create объявлять как new? почему обычный create не устраивает?

2021-07-07 09:22 UTC, Alex-Govorov commented on config/routes.rb
> +      post :create, path: ':value', on: :member, as: :new
Т.к. в create у нас используется дополнительный параметер value и если его не отделить в отдельный хелпер, то тогда Url генератор будет ругаться на missing required keys: [:value] при попытки использовать хелпер answer_vote для show и destroy, где этот параметер не используется.
```
                         new_answer_vote POST   /answers/:answer_id/vote/:value(.:format)                                                         votes#create
                             answer_vote GET    /answers/:answer_id/vote(.:format)                                                                votes#show
                                         DELETE /answers/:answer_id/vote(.:format)                                                                votes#destroy
                       new_question_vote POST   /questions/:question_id/vote/:value(.:format)                                                     votes#create
                           question_vote GET    /questions/:question_id/vote(.:format)                                                            votes#show
                                         DELETE /questions/:question_id/vote(.:format)                                                            votes#destroy

```

2021-07-07 09:25 UTC, Alex-Govorov commented on app/controllers/votes_controller.rb
> +    vote_response = {}
Да, логично - переделал.

2021-07-07 09:48 UTC, merged